### ISSUE TITLE
Refactor directions with State patterns

### ISSUE THREAD

**Issue by lbeaufort** [lbeaufort/mars-rover#1]
Instead of our `if` statements for changing directions, make cardinal direction classes that each have a `turn_left` and `turn_right` 

```
Class North:
    def .....
```

**Comment by Creeland** [comment]
![image](https://user-images.githubusercontent.com/518406/39649979-7a890338-4fb4-11e8-9314-db5debced3e3.png)

**Comment by lbeaufort** [comment]
Addressed by PR: https://github.com/lbeaufort/mars-rover/pull/4
